const builtFeatures = [
  {
    emoji: "🧠",
    title: "AI Training Plans",
    body: "Generated, evaluated, and regenerated by Claude AI based on your InBody scan data. Adapts every 4–8 weeks as your body changes.",
  },
  {
    emoji: "📋",
    title: "Body Composition Tracking",
    body: "Import InBody scan results directly. Track body fat %, muscle mass, and metabolic rate over time with trend charts.",
  },
  {
    emoji: "⚡",
    title: "Live Session Tracking",
    body: "Log sets, reps, and weights in real-time. Auto-detects personal records. Built-in rest timer. Works offline.",
  },
  {
    emoji: "🍎",
    title: "Apple Health Integration",
    body: "Workouts sync to Apple Health automatically. Body weight pre-fills from your latest Apple Health data.",
  },
  {
    emoji: "🏆",
    title: "Personal Records",
    body: "Auto-detected from session history. Per-exercise trend charts show your strength progression over time.",
  },
  {
    emoji: "📅",
    title: "Smart Weekly Schedule",
    body: "Structured week built for hybrid athletes: rest, strength, and cardio days laid out with AI plan days and completion tracking.",
  },
  {
    emoji: "📚",
    title: "Exercise Library",
    body: "17 exercises with muscle diagrams, step-by-step instructions, and AI-powered substitutions when you need them.",
  },
  {
    emoji: "🔥",
    title: "Streak & Volume Tracking",
    body: "Week-based streak tracker, session volume chart, and calendar heatmap keep your consistency front and centre.",
  },
];

const comingSoonFeatures = [
  {
    emoji: "🏋️",
    title: "1RM + Volume Load Tracking",
    body: "Estimated one-rep max via Epley formula. Weekly volume load per muscle group. Plate calculator included.",
  },
  {
    emoji: "💪",
    title: "Muscle Fatigue Model",
    body: "Per-muscle fatigue that decays over 48–72 hours. HomeView shows muscle freshness for today's session and ranks substitutions accordingly.",
  },
  {
    emoji: "😴",
    title: "Deload Week Detection",
    body: "After 3+ high-volume weeks or declining HRV, Forge auto-generates a deload week at 60% volume — same movements, less load.",
  },
  {
    emoji: "❤️",
    title: "HRV from Apple Watch",
    body: "7-day rolling HRV average from Apple Watch feeds into your plan lifecycle to make recovery intelligence objective, not self-reported.",
  },
  {
    emoji: "🧘",
    title: "Warm-up & Cool-down Protocols",
    body: "Claude adds structured warm-up and cool-down blocks per workout type as dedicated exercises in every session.",
  },
  {
    emoji: "📸",
    title: "Progress Photos",
    body: "Photo log tied to InBody scan dates — put your body comp numbers alongside a photo from the same day. Stored locally only.",
  },
];

export default function Features() {
  return (
    <section className="section-reveal px-6 py-24 max-w-6xl mx-auto">
      {/* Section tag */}
      <p className="text-xs font-bold tracking-widest uppercase text-orange-500 mb-4">
        Features
      </p>

      {/* Headline */}
      <h2 className="text-4xl md:text-5xl lg:text-6xl font-black uppercase leading-tight mb-4">
        Everything you need.
        <br />
        <span className="text-white/50">Nothing you don&apos;t.</span>
      </h2>

      {/* Live now label */}
      <div className="flex items-center gap-2 mb-10">
        <span className="inline-block w-2 h-2 rounded-full bg-emerald-400 animate-pulse-slow" />
        <span className="text-xs font-bold tracking-widest uppercase text-emerald-400">
          Live Now
        </span>
      </div>

      {/* Built feature grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-20">
        {builtFeatures.map((feature) => (
          <div
            key={feature.title}
            className="feature-card rounded-2xl p-7 bg-[#111] border border-[#1e1e1e]"
          >
            <span className="text-3xl mb-4 block">{feature.emoji}</span>
            <h3 className="text-base font-black uppercase tracking-wide text-white mb-2">
              {feature.title}
            </h3>
            <p className="text-sm text-white/60 leading-relaxed">{feature.body}</p>
          </div>
        ))}
      </div>

      {/* Coming soon divider */}
      <div className="flex items-center gap-4 mb-10">
        <div className="h-px flex-1 bg-[#1e1e1e]" />
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold tracking-widest uppercase text-orange-500/70">
            Coming Soon
          </span>
        </div>
        <div className="h-px flex-1 bg-[#1e1e1e]" />
      </div>

      <p className="text-sm text-white/40 mb-10 max-w-xl">
        Already in development. These features unlock progressively as your training history grows.
      </p>

      {/* Coming soon grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {comingSoonFeatures.map((feature) => (
          <div
            key={feature.title}
            className="feature-card relative rounded-2xl p-7 bg-[#0d0d0d] border border-[#1a1a1a] overflow-hidden"
          >
            {/* Subtle coming-soon badge */}
            <span className="absolute top-4 right-4 text-[10px] font-bold tracking-widest uppercase text-orange-500/50 border border-orange-500/20 rounded-full px-2 py-0.5">
              Soon
            </span>
            <span className="text-3xl mb-4 block opacity-60">{feature.emoji}</span>
            <h3 className="text-base font-black uppercase tracking-wide text-white/60 mb-2">
              {feature.title}
            </h3>
            <p className="text-sm text-white/35 leading-relaxed">{feature.body}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
