const features = [
  {
    emoji: "🧠",
    title: "AI Training Plans",
    body: "Generated, evaluated, and regenerated by artificial intelligence based on your body composition and session performance.",
  },
  {
    emoji: "📋",
    title: "Body Composition Tracking",
    body: "Import your scan results directly. Track body fat %, muscle mass, and metabolic rate over time with trend charts.",
  },
  {
    emoji: "⚡",
    title: "Live Session Tracking",
    body: "Log sets, reps, and weights in real-time. Auto-detects personal records. Rest timer built in. Works offline.",
  },
  {
    emoji: "🍎",
    title: "Apple Health Integration",
    body: "Workouts sync to Apple Health automatically. Body weight pre-fills from your latest Apple Health data.",
  },
  {
    emoji: "🏆",
    title: "Personal Records",
    body: "Auto-detected from your session history. Per-exercise trend charts show your strength progression over time.",
  },
  {
    emoji: "📚",
    title: "Exercise Library",
    body: "52 exercises with muscle diagrams, step-by-step instructions, and AI-powered substitutions when you need them.",
  },
];

export default function Features() {
  return (
    <section className="px-6 py-24 max-w-6xl mx-auto">
      {/* Section tag */}
      <p className="text-xs font-bold tracking-widest uppercase text-orange-500 mb-4">
        Features
      </p>

      {/* Headline */}
      <h2 className="text-4xl md:text-5xl lg:text-6xl font-black uppercase leading-tight mb-16">
        Everything you need.
        <br />
        <span className="text-white/50">Nothing you don&apos;t.</span>
      </h2>

      {/* Feature grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {features.map((feature) => (
          <div
            key={feature.title}
            className="rounded-2xl p-7 bg-[#111] border border-[#1e1e1e] hover:border-orange-500/30 transition-colors duration-300"
          >
            <span className="text-3xl mb-4 block">{feature.emoji}</span>
            <h3 className="text-base font-black uppercase tracking-wide text-white mb-2">
              {feature.title}
            </h3>
            <p className="text-sm text-white/60 leading-relaxed">{feature.body}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
